import Head from 'next/head';
import LogoSVG from '../assets/SVGS/LogoSVG';
import Menu from '../assets/SVGS/Humberger';
import Navbar from '../Components/Navbar';
import Section1 from '../Components/Section1';
import About from '../Components/About';
import Skills from '../Components/Skills';
import RecentWorks from '../Components/RecentWorks';
export default function Home() {
  return (
    <>
      <Head>
        <title>Francis</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className='section-center'>
          <div className='md:hidden flex justify-between items-center pt-8'>
            <LogoSVG />
            <button>
              <Menu />
            </button>
          </div>
          <Navbar />
          <Section1 />
          <About />
          <Skills />
          <RecentWorks />
        </div>
      </main>
    </>
  );
}
